/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    ChatIcon: typeof import('./../components/icons/ChatIcon.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ColorModeToggle: typeof import('./../components/ColorModeToggle.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ConfirmDialog: typeof import('./../components/confirmDialog/ConfirmDialog.vue')['default']
    CookieInformation: typeof import('./../components/notifier/cookieConsent/cookieInformation.vue')['default']
    CookiePreferencesDialog: typeof import('./../components/notifier/cookieConsent/cookiePreferencesDialog.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DiamondIcon: typeof import('./../components/icons/DiamondIcon.vue')['default']
    DiscordChatIcon: typeof import('./../components/icons/DiscordChatIcon.vue')['default']
    DiscordIcon: typeof import('./../components/icons/DiscordIcon.vue')['default']
    DiscordIconOutlined: typeof import('./../components/icons/DiscordIconOutlined.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Iconify: typeof import('./../components/icons/Iconify.vue')['default']
    InputLabel: typeof import('./../components/inputLabel.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LimitReachedAlert: typeof import('./../components/notifier/limitReachedAlert.vue')['default']
    LoadingIcon: typeof import('./../components/icons/loadingIcon.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiButton: typeof import('./../components/MultiButton.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Notifier: typeof import('./../components/notifier/notifier.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    ShopIcon: typeof import('./../components/icons/ShopIcon.vue')['default']
    SiteFooter: typeof import('./../components/siteFooter.vue')['default']
    SiteHeader: typeof import('./../components/siteHeader.vue')['default']
    SiteNav: typeof import('./../components/siteNav.vue')['default']
    StatusBadge: typeof import('./../components/StatusBadge.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
